#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias px="proxychains"
alias vue-ui="cd /opt/var/data/vue/ && nohup vue ui >> vue-ui.log &"
alias bd="baidupcs"
alias la="ls -al"
alias pj="cd /opt/projects/"
alias www="cd /opt/projects/www/"
